### ISSUE TITLE
Detail Sceneの実装

### ISSUE THREAD

**Issue by rerost** [enpit-ateam/Prunner4iOS#25]
- 前提
https://github.com/enpit-ateam/Prunner4iOS/pull/22, https://github.com/enpit-ateam/Prunner4iOS/pull/24 がマージされている

- モック
![2016-12-04 18 48 56](https://cloud.githubusercontent.com/assets/5201588/20865347/73f94396-ba52-11e6-8755-ac2851955fef.png)

- 実装
- [x] マップの表示
- [x] ルートをマップ上に表示
- [x] 走った距離などを表示

**Comment by kobayang** [comment]
#26 が mergeされたので close.
> Doneページで走った距離の保存

保存は完了しているので削除機能を必要であれば別Issueで作成する
