### ISSUE TITLE
ビューの分離

### ISSUE THREAD

**Issue by kobayang** [enpit-ateam/Prunner4iOS#8]
入力部分とマップ表示部分でViewControllerが一緒になっているので
それぞれ別々に実装するようにしたい

疑問点：
遷移した時の記述はStoryBoardのSegueで書くのがいいか、
ViewController上で書くほうがいいか、

**Comment by kobayang** [comment]
`ViewController.swift`を入力画面(`InputDistanceViewController.swift`)とマップ画面(`PrunnerMapViewController.swift`)に分けて、画面遷移をStoryBoard上のSegueで行うようにした。

コードの記述内容には変更はないが、なぜかMap上にMakerが表示されなくなってしまった。
`Session`が非同期で行われていて、データを取得する前に`viewDidLoad`が終了している可能性がある

解決策：
- Swift GCDを使う
- RxSwiftを使う

**Comment by nullcast** [comment]
makerが表示されない問題の原因がわかりました。
現状makerの表示はviewDidLoad内で呼んでますが、現在座標を取得する前にsetMapViewを呼んでいるために、カメラ座標が更新されないうちにその時点でのPlaceを求め、その後、自分の座標にカメラが移動しているのが原因だとわかりました。
解決法としては、現在座標を取得した後に、1度だけsetMapViewを呼ぶのがベストです。
特に最初の距離を入力するViewControllerの時点で現在座標を取得しておき、それを次のViewControllerに渡す方がいいかもしれません。

**Comment by kobayang** [comment]
close.
